// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Block extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Block __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Index to the start of the RecordBlock (note this is past the Message header)
   */
  public long offset() { return bb.getLong(bb_pos + 0); }
  /**
   * Length of the metadata
   */
  public int metaDataLength() { return bb.getInt(bb_pos + 8); }
  /**
   * Length of the data (this is aligned so there can be a gap between this and
   * the metatdata).
   */
  public long bodyLength() { return bb.getLong(bb_pos + 16); }

  public static int createBlock(FlatBufferBuilder builder, long offset, int metaDataLength, long bodyLength) {
    builder.prep(8, 24);
    builder.putLong(bodyLength);
    builder.pad(4);
    builder.putInt(metaDataLength);
    builder.putLong(offset);
    return builder.offset();
  }
}

