// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

public final class DateUnit {
  private DateUnit() { }
  public static final short DAY = 0;
  public static final short MILLISECOND = 1;

  public static final String[] names = { "DAY", "MILLISECOND", };

  public static String name(int e) { return names[e]; }
}

