// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

/**
 * ----------------------------------------------------------------------
 * Dictionary encoding metadata
 * Maintained for forwards compatibility, in the future
 * Dictionaries might be explicit maps between integers and values
 * allowing for non-contiguous index values
 */
public final class DictionaryKind {
  private DictionaryKind() { }
  public static final short DenseArray = 0;

  public static final String[] names = { "DenseArray", };

  public static String name(int e) { return names[e]; }
}

