// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

/**
 * ----------------------------------------------------------------------
 * Endianness of the platform producing the data
 */
public final class Endianness {
  private Endianness() { }
  public static final short Little = 0;
  public static final short Big = 1;

  public static final String[] names = { "Little", "Big", };

  public static String name(int e) { return names[e]; }
}

