// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

public final class IntervalUnit {
  private IntervalUnit() { }
  public static final short YEAR_MONTH = 0;
  public static final short DAY_TIME = 1;

  public static final String[] names = { "YEAR_MONTH", "DAY_TIME", };

  public static String name(int e) { return names[e]; }
}

