// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * Same as Binary, but with 64-bit offsets, allowing to represent
 * extremely large data values.
 */
public final class LargeBinary extends Table {
  public static LargeBinary getRootAsLargeBinary(ByteBuffer _bb) { return getRootAsLargeBinary(_bb, new LargeBinary()); }
  public static LargeBinary getRootAsLargeBinary(ByteBuffer _bb, LargeBinary obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public LargeBinary __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startLargeBinary(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endLargeBinary(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

