// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

/**
 * ----------------------------------------------------------------------
 * The root Message type
 * This union enables us to easily send different message types without
 * redundant storage, and in the future we can easily add new message types.
 *
 * Arrow implementations do not need to implement all of the message types,
 * which may include experimental metadata types. For maximum compatibility,
 * it is best to send data using RecordBatch
 */
public final class MessageHeader {
  private MessageHeader() { }
  public static final byte NONE = 0;
  public static final byte Schema = 1;
  public static final byte DictionaryBatch = 2;
  public static final byte RecordBatch = 3;
  public static final byte Tensor = 4;
  public static final byte SparseTensor = 5;

  public static final String[] names = { "NONE", "Schema", "DictionaryBatch", "RecordBatch", "Tensor", "SparseTensor", };

  public static String name(int e) { return names[e]; }
}

