// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * Compressed Sparse format, that is matrix-specific.
 */
public final class SparseMatrixIndexCSX extends Table {
  public static SparseMatrixIndexCSX getRootAsSparseMatrixIndexCSX(ByteBuffer _bb) { return getRootAsSparseMatrixIndexCSX(_bb, new SparseMatrixIndexCSX()); }
  public static SparseMatrixIndexCSX getRootAsSparseMatrixIndexCSX(ByteBuffer _bb, SparseMatrixIndexCSX obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public SparseMatrixIndexCSX __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Which axis, row or column, is compressed
   */
  public short compressedAxis() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  /**
   * The type of values in indptrBuffer
   */
  public Int indptrType() { return indptrType(new Int()); }
  public Int indptrType(Int obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * indptrBuffer stores the location and size of indptr array that
   * represents the range of the rows.
   * The i-th row spans from indptr[i] to indptr[i+1] in the data.
   * The length of this array is 1 + (the number of rows), and the type
   * of index value is long.
   *
   * For example, let X be the following 6x4 matrix:
   *
   *   X := [[0, 1, 2, 0],
   *         [0, 0, 3, 0],
   *         [0, 4, 0, 5],
   *         [0, 0, 0, 0],
   *         [6, 0, 7, 8],
   *         [0, 9, 0, 0]].
   *
   * The array of non-zero values in X is:
   *
   *   values(X) = [1, 2, 3, 4, 5, 6, 7, 8, 9].
   *
   * And the indptr of X is:
   *
   *   indptr(X) = [0, 2, 3, 5, 5, 8, 10].
   */
  public Buffer indptrBuffer() { return indptrBuffer(new Buffer()); }
  public Buffer indptrBuffer(Buffer obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  /**
   * The type of values in indicesBuffer
   */
  public Int indicesType() { return indicesType(new Int()); }
  public Int indicesType(Int obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  /**
   * indicesBuffer stores the location and size of the array that
   * contains the column indices of the corresponding non-zero values.
   * The type of index value is long.
   *
   * For example, the indices of the above X is:
   *
   *   indices(X) = [1, 2, 2, 1, 3, 0, 2, 3, 1].
   *
   * Note that the indices are sorted in lexicographical order for each row.
   */
  public Buffer indicesBuffer() { return indicesBuffer(new Buffer()); }
  public Buffer indicesBuffer(Buffer obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startSparseMatrixIndexCSX(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addCompressedAxis(FlatBufferBuilder builder, short compressedAxis) { builder.addShort(0, compressedAxis, 0); }
  public static void addIndptrType(FlatBufferBuilder builder, int indptrTypeOffset) { builder.addOffset(1, indptrTypeOffset, 0); }
  public static void addIndptrBuffer(FlatBufferBuilder builder, int indptrBufferOffset) { builder.addStruct(2, indptrBufferOffset, 0); }
  public static void addIndicesType(FlatBufferBuilder builder, int indicesTypeOffset) { builder.addOffset(3, indicesTypeOffset, 0); }
  public static void addIndicesBuffer(FlatBufferBuilder builder, int indicesBufferOffset) { builder.addStruct(4, indicesBufferOffset, 0); }
  public static int endSparseMatrixIndexCSX(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 6);  // indptrType
    builder.required(o, 8);  // indptrBuffer
    builder.required(o, 10);  // indicesType
    builder.required(o, 12);  // indicesBuffer
    return o;
  }
}

