// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

public final class SparseTensorIndex {
  private SparseTensorIndex() { }
  public static final byte NONE = 0;
  public static final byte SparseTensorIndexCOO = 1;
  public static final byte SparseMatrixIndexCSX = 2;

  public static final String[] names = { "NONE", "SparseTensorIndexCOO", "SparseMatrixIndexCSX", };

  public static String name(int e) { return names[e]; }
}

