// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

public final class TimeUnit {
  private TimeUnit() { }
  public static final short SECOND = 0;
  public static final short MILLISECOND = 1;
  public static final short MICROSECOND = 2;
  public static final short NANOSECOND = 3;

  public static final String[] names = { "SECOND", "MILLISECOND", "MICROSECOND", "NANOSECOND", };

  public static String name(int e) { return names[e]; }
}

