// automatically generated by the FlatBuffers compiler, do not modify

package jarrow.fbs.arrow;

public final class UnionMode {
  private UnionMode() { }
  public static final short Sparse = 0;
  public static final short Dense = 1;

  public static final String[] names = { "Sparse", "Dense", };

  public static String name(int e) { return names[e]; }
}

