// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf;

public final class Precision {
  private Precision() { }
  public static final short HALF = 0;
  public static final short SINGLE = 1;
  public static final short DOUBLE = 2;

  public static final String[] names = { "HALF", "SINGLE", "DOUBLE", };

  public static String name(int e) { return names[e]; }
}

