// automatically generated by the FlatBuffers compiler, do not modify

package org.apache.arrow.flatbuf;

public final class SparseMatrixCompressedAxis {
  private SparseMatrixCompressedAxis() { }
  public static final short Row = 0;
  public static final short Column = 1;

  public static final String[] names = { "Row", "Column", };

  public static String name(int e) { return names[e]; }
}

